In [1]:
# Import libraries

import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
# Read collected data
df1 = pd.read_csv("../data/recipes_Indian_df.csv", index_col="Unnamed: 0").reset_index(drop=True)
df2 = pd.read_csv("../data/recipes_Spanish_df.csv", index_col="Unnamed: 0").reset_index(drop=True)
df3 = pd.read_csv("../data/recipes_Italian_df.csv", index_col="Unnamed: 0").reset_index(drop=True)
df4 = pd.read_csv("../data/recipes_vegan_df.csv", index_col="Unnamed: 0").reset_index(drop=True)
df5 = pd.read_csv("../data/recipes_Mexican_df.csv", index_col="Unnamed: 0").reset_index(drop=True)

# I will review and clean each dataframe separately, because the data types in equivalent 
# columns differ (Kcal column might be float or string, depending on when I scraped the data
# and how I tweaked the scraper). 
# Rescraping (politely!) all the data would be too time consuming at this point.

In [3]:
# The nutritional values should be float. Data needs some cleaning.

# There are some rows without nutritional information. I will drop them, as there are enough
# recipes to analyse with complete rows.

print(df1.dtypes, df1.isnull().sum())

Title             object
Ingredients       object
Kcal              object
Fat              float64
SaturatedFat      object
Protein          float64
Carbohydrates    float64
Sugars            object
Fibre             object
Salt              object
Country           object
dtype: object Title            0
Ingredients      0
Kcal             8
Fat              8
SaturatedFat     8
Protein          8
Carbohydrates    8
Sugars           8
Fibre            8
Salt             8
Country          0
dtype: int64

In [4]:
df1 = df1.dropna()
df1.shape

(88, 11)

In [5]:
# Looking at nutrition columns with data type 'object'
print((df1['Kcal']).tolist(), "\n\n", (df1['SaturatedFat']).tolist(), "\n\n", 
      (df1['Sugars']).tolist(),"\n\n", (df1['Fibre']).tolist(), "\n\n", 
      (df1['Salt']).tolist())

['201', '478', '112', '357', '402', '121', '386kcal', '137', '411', '370', '67', '398', '130', '8', '517', '203', '114', '513', '219', '360.0', '577.0', '269.0', '625.0', '195.0', '569.0', '368.0', '433.0', '417.0', '291.0', '832.0', '307.0', '421.0', '398.0', '252.0', '217.0', '245.0', '692.0', '143.0', '412.0', '90.0', '319.0', '312.0', '401.0', '408.0', '241.0', '624.0', '379.0', '556.0', '583.0', '697.0', '613.0', '316.0', '327.0', '381.0', '626.0', '320', '196', '359', '379', '509', '38', '148', '421', '422kcal', '446', '73', '144', '461', '265', '264', '465', '339', '192', '276.0', '368.0', '659.0', '243.0', '461.0', '489.0', '375.0', '440.0', '675.0', '576.0', '418.0', '198.0', '347.0', '617.0', '443.0']

 ['5.6', '2.7', '2.3', '2.3', '8.3', '1.9', '9.1', '1.4', '5.3', '7.2', '0.2', '6.8', '2.9', 'trace', '9.5', '3.7', '0.4', '8.5', '1', '2.6', '31.4', '19.7', '18.8', '0.8', '9.7', '4.6', '6.7', '3.4', '10.6', '21.0', '11.4', '2.5', '10.6', '0.9', '8.4', '5.8', '28.6', '2.3', '6.0', '3.3', '6.6', '4.4', '2.4', '3.1', '4.6', '19.1', '5.9', '5.0', '9.0', '4.7', '12.1', '6.5', '9.4', '5.7', '18.0', '3.7', '0.9', '2.3', '4.2', '15.5', '0.4', '0.8', '15.9', '3.5', '4.3', '0.2', '2.4', '4.7', '0.7', '0.8', '10.2', '0.6', '5.0', '3.8', '5.6', '21.8', '0.7', '2.7', '1.4', '8.7', '15.9', '32.9', '13.6', '6.7', '6.0', '19.6', '4.5', '10.0']

 ['6.6', '7.9', '3.7', '10.9', '9.6', '9.1', '5.6', '14.2', '6.8', '10.3', '4.8', '14.7', '18.0', '0.1', '5.9', '2.9', '9.6', '5.5', '0.5', '8.4', '8.7', '4.7', '13.3', '8.1', '14.6', '3.6', '4.7', '8.2', '5.3', '9.6', '5.2', '8.3', '5.5', '12.7', '5.6', '4.6', '9.8', '0.6', '12.9', '3.1', '8.1', '6.9', '3.4', '14.3', '0.3', '16.4', '3.0', '17.2', '7.0', '10.5', '10.6', '1.7', '6.5', '13.1', '6.8', '13.5', '10', '12.6', '5.3', '18.2', '1.4', '8.9', '17.8', '3', '24.5', '1', '2.7,', '20.3', '3.5', '8.9', '9.7', '14.2', '1.6', '10.5', '24.6', '19.6', '1.4', '17.5', '17.9', '16.2', '32.0', '26.4', '7.1', '4.6', '14.8', '0.3', '11.8', '6.5']

 ['2.4', '4', '2', '7.1', '4.9', 'trace', '7', '0.1', '4.4', '5.7', '1.3', '4', '0.1', '0.2', '2.6', '3.3', '1.7', '3.7', '2.1', '5.9', '4.3', '1.4', '8.0', '3.3', '9.6', '4.9', '3.4', '7.2', '2.5', '5.7', '1.8', '5.2', '12.7', '10.0', '5.6', '2.6', '4.3', '1.1', '8.9', '0.5', '4.4', '2.0', '2.5', '9.9', '1.9', '4.2', '1.1', '17.3', '9.4', '4.2', '7.3', '4.1', '3.9', '8.4', '6.4', '6.2', '5.4', '9.5', '3', '13', 'no fibre', '7', '6.5', '1.8', '15.7', '1.4', '3.7', '11.7', '4.4', '9.4', '5.7', '11', '1.8', '4.9', '9.7', '12.8', '3.8', '15.3', '15.4', '9.6', '3.4', '1,9', '3.5', '3.4', 'no fibre', '0.2', '8', '10.2']

 ['0.1', '0.8', '0.5', '0.6', '1.1', '0.1', '0.3', '0.3', '0.8', 'trace', '0.1', '1.1', '0.1', '0.1', '2.5', '0.8', '0.4', '3.2', '1.5', '0.4', '0.4', '0.1', '1.1', '0.4', '3.0', '0.6', '0.7', '2.8', '0.2', '2.1', '0.35', '0.7', '0.2', '0.1', '1.0', '0.6', '0.1', '0.5', '1.2', '0.2', '0.6', '0.6', '0.7', '1.2', '0.8', '1.0', '1.4', '0.2', '0.3', '1.6', '0.4', '1.2', '2.4', '1.5', '1.1', '0.4', '2.3', '0.5', '1.6', '0.4', '0.2', '1.4', '1.0', '1.5', '0.7', '0.4', '4.5', '1.3', '1.3', '1.1', '0.6', '0.3', '0.4', '0.8', '0.6', '1.7', '0.8', '1.1', '0.3', '0.2', '0.3', '0.1', '0.8', '0.8', '0.2', '0.6', '0.7', '0.3']

In [6]:
# Cleaning up nutrition columns df1

# Removing unwanted characters 
df1['Kcal'] = df1['Kcal'].str.replace('kcal', '')
df1['SaturatedFat'] = df1['SaturatedFat'].str.replace('trace', '0')
df1['Sugars'] = df1['Sugars'].str.replace(',', '')
df1['Fibre'] = df1['Fibre'].str.replace('trace', '0')
df1['Fibre'] = df1['Fibre'].str.replace(',', '')
df1['Fibre'] = df1['Fibre'].str.replace('no fibre', '0')
df1['Salt'] = df1['Salt'].str.replace('trace', '0')

# Turning data into float
df1['Kcal'] = df1['Kcal'].astype('float64')
df1['SaturatedFat'] = df1['SaturatedFat'].astype('float64')
df1['Sugars'] = df1['Sugars'].astype('float64')
df1['Fibre'] = df1['Fibre'].astype('float64')
df1['Salt'] = df1['Salt'].astype('float64')

# data.astype({'Kcal': 'float64', 'SaturatedFat': 'float64', 'Sugars': 'float64', 'Fibre': 'float64', 'Salt':'float64' })

print(df1.dtypes)

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein          float64
Carbohydrates    float64
Sugars           float64
Fibre            float64
Salt             float64
Country           object
dtype: object

In [7]:
# Cleaning up nutrition columns df2

print(df2.dtypes, df2.isnull().sum())
df2 = df2.dropna()

# Looking at nutrition columns with data type 'object'
print((df2['Carbohydrates']).tolist(), "\n\n", (df2['Fibre']).tolist(), "\n\n", 
      (df2['Salt']).tolist())

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein          float64
Carbohydrates     object
Sugars           float64
Fibre             object
Salt              object
Country           object
dtype: object Title             0
Ingredients       0
Kcal             16
Fat              16
SaturatedFat     16
Protein          16
Carbohydrates    16
Sugars           16
Fibre            16
Salt             16
Country           0
dtype: int64
['50.9', '12.0', '63.6', '36.5', '38.1', '14.5', '49.9', '5.5', '5.3', '13.0', '36.2', '17.6', '18.3', '22.1', '43.1', '15.4', '34.9', '40.6', '8.8', '8.8', '51.9', '50.5', '19.4', '52.9', '10.5', '17.8', '31.7', '50.4', '51.2', '57.2', '50.7', '66.1', '3.1', '10.0', '87.8', '14.9', '14.9', '14.0', '21.0', '9.7', '21.5', '7.3', '6.0', '29.4', '19.4', '6.7', '22.5', '6.6', '52.7', '2', '60.3', '5.4', '19.4', '66.3', '17.7', '7 carbs', '3.5', '81 carbs', '69.6', '4.8', '33.2', '16.6', '56.4 carbs', '30.1', '11.5', '6.2', '15.5', '14.5', '59.3', '10.6', '12.4', '2.9', '8.8', '20.6', '22.4', '22.4', '14.1', '13.6', '3.1', '6.0', '6.3', '4.3', '24.1', '26.5']

 ['14.7', '1.6', '6.3', '7.9', '2.7', '6.1', '10.2', '3.3', '0.5', '5.8', '3.5', '3.4', '8.3', '2.4', '5.9', '4.4', '0.7', '4.6', '3.7', '2.8', '3.5', '1.4', '5.8', '5.6', '0.6', '0.7', '5.4', '9.4', '11.8', '1.0', '1.4', '4.6', '2.5', '2.9', '13.3', '5.1', '4.6', '0.6', '4.5', '5.2', '3.0', '0.7', '3.4', '10.2', '10.4', '3.1', '5.0', '0.5', '5.3', '1.4', '4.7', '3.4', '9.8', '6.2', '9.2', '0.1', 'nil', '8.3', '4.5', '0.6', '11.8', '4', '1.7', '9.8', '3', '0.3', '3.8', '5.4', '7.2', '3.7', '1.2', '1.2', '7', '3.1', '6.3', '6.3', '4', '5.3', '2.6', '1.1', '0.3', 'None', '4.2 fibre', '11']

 ['1.2', '1.2', '0.8', '0.6', '1.4', '1.2', '2.3', '0.9', '0.7', '1.0', '2.2', '1.6', '1.7', '0.3', '0.1', '0.1', '0.3', '1.3', '0.8', 'trace salt', '1.3', '2.8', '2.1', '1.7', '0.2', '1.9', '5.3', '0.8', '1.5', '0.9', '2.1', '2.3', '0.4', '0.6', '2.3 salt', '1.3', '2.6', '0.2', '0.6', '0.2', '5.6', '1.8', '1.3', '3.1', '2.2', '1.4', '2.7', '0.4', '2.4', '0.7', '3.0', '1.0', '1.9', '1.7', '2.8', '0.1', '0.1', '0.8', '1.6', '1.8', '2.0', '1.4', '0.4', '1.4', '0.5', '0.3', '2.6', '0.1', '1.5', '0.8', '0.6', '0.3', '1.8', '1.1', '2.5', '2.5', '1', '3.1', '1.4', '1.3', '0.2', '1.4', '0.1 salt', '2.7']

In [8]:
# Cleaning up nutrition columns df2

# Removing unwanted characters
df2['Carbohydrates'] = df2['Carbohydrates'].str.replace(' carbs', '')

df2['Fibre'] = df2['Fibre'].str.replace(' fibre', '')
df2['Fibre'] = df2['Fibre'].str.replace('None', '0')
df2['Fibre'] = df2['Fibre'].str.replace('nil', '0')

df2['Salt'] = df2['Salt'].str.replace('trace salt', '0')
df2['Salt'] = df2['Salt'].str.replace(' salt', '')

# Turning data into float
df2['Carbohydrates'] = df2['Carbohydrates'].astype('float64')
df2['Fibre'] = df2['Fibre'].astype('float64')
df2['Salt'] = df2['Salt'].astype('float64')

print(df2.dtypes)

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein          float64
Carbohydrates    float64
Sugars           float64
Fibre            float64
Salt             float64
Country           object
dtype: object

In [9]:
# Cleaning up nutrition columns df2

print(df3.dtypes, df3.isnull().sum())
df3 = df3.dropna()

# Looking at nutrition columns with data type 'object'
print((df3['Protein']).tolist(),"\n\n", 
      (df3['Salt']).tolist())

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein           object
Carbohydrates    float64
Sugars           float64
Fibre            float64
Salt              object
Country           object
dtype: object Title            0
Ingredients      0
Kcal             8
Fat              8
SaturatedFat     8
Protein          8
Carbohydrates    8
Sugars           8
Fibre            8
Salt             8
Country          0
dtype: int64
['5.9', '2.3', '23.7', '13.2', '0.8', '18.0', '26.0', '37.5', '40.0', '23.7', '23.7', '19.3', '1.9', '13.1', '25.3', '26.2', '25.0', '36.5', '36.4', '11.8', '12.7', '24.3', '40.5', '7.6', '11.1', '15.1', '7.3', '14.3', '13.4', '26', '3.8', '4.5', '30.3', '17.2', '23.523.5', '16.2', '14.9', '11.5', '19', '16.6', '16.3', '9.6', '35.6', '26.2', '30.2', '14.6', '16.9', '23.0', '17.7', '24.9', '31.8', '24.3', '47.3', '2.2', '40.9', '6.1', '7.3', '13.6', '22.4', '18.3', '15.0', '13.5', '31.0', '30.9', '18.7', '33.4', '37.2', '5.7', '20.2', '27.0', '15.0', '12.6', '54.4', '8.6', '32.1', '17.7', '1.4', '23.1', '43.8', '30.4', '8.4', '47.1', '2.1', '23.1', '31.2', '17.0', '32.9', '6.7']

 ['0.5', '0.1', '1.3', '0.6', '0.1', '0.2', '2.1', '0.9', '1.3', '1.0', '1.0', '0.6', '0.9', '1.0', '1.2', '1.9', '0.7', '3.8', '3.7', '1.1', '0.4', '1.1', '3.1', '0.8', '0.4', '2.6', '0.1', '2', '1.6', '1.9', '1.2', 'trace', '1.9', '0.2', '0.4', '1', '1', '0.6', '0.4', '0.5', '0.6', '0.2', '0.4', '0.8', '5.0', '0.7', '0.3', '0.76', '4.0', '1.7', '0.9', '2.1', '5.2', '0.4', '2.4', '0.6', '0.3', '1.9', '2.1', '0.2', '0.4', '0.5', '1', '1.9', '2.3', '0.9', ',2.4', '0.5', '2.3', '0.7', '0.3', '1.6', '0.82', '0.2', '1.5', '1', '0.3', '0.8', '1.7', '0.8', '0.4', '0.9', '0.6', '1.6', '1.2', '0.7', '0.8', '0.6']

In [10]:
# One value in Protein looked odd. The table on the website repeated the same value twice.

print(df3.loc[df3['Protein'] == '23.523.5'].index)
df3.loc[39, 'Protein'] = '23.5'

Int64Index([39], dtype='int64')

In [11]:
# Cleaning up nutrition columns df3

# Removing unwanted characters
df3['Salt'] = df3['Salt'].str.replace('trace', '0')
df3['Salt'] = df3['Salt'].str.replace(',', '')

# Turning data into float
df3['Protein'] = df3['Protein'].astype('float64')
df3['Salt'] = df3['Salt'].astype('float64')

print(df3.dtypes)

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein          float64
Carbohydrates    float64
Sugars           float64
Fibre            float64
Salt             float64
Country           object
dtype: object

In [12]:
# Cleaning up nutrition columns df4

print(df4.dtypes, df4.isnull().sum())
df4 = df4.dropna()

# Looking at nutrition columns with data type 'object'

print((df4['Kcal']).tolist(), "\n\n", (df4['SaturatedFat']).tolist(), "\n\n", 
      (df4['Carbohydrates']).tolist(),"\n\n", (df4['Fibre']).tolist(), "\n\n", 
      (df4['Salt']).tolist())

Title             object
Ingredients       object
Kcal              object
Fat              float64
SaturatedFat      object
Protein          float64
Carbohydrates     object
Sugars           float64
Fibre             object
Salt              object
Country           object
dtype: object Title            0
Ingredients      0
Kcal             5
Fat              5
SaturatedFat     5
Protein          5
Carbohydrates    5
Sugars           5
Fibre            5
Salt             5
Country          0
dtype: int64
['243', '35', '482', '562', '537', '445', '90', '351', '510', '616', '93', '65', '130', '329', '291', '216', '386kcal', '370.0', '67.0', '262.0', '412.0', '240.0', '126.0', '113.0', '24.0', '8.0', '114.0', '242.0', '317.0', '157.0', '224.0', '230.0', '248.0', '73.0', '556.0', '497', '450', '529', '596', '263', '280', '184', '364', '503', '252', '375', '252', '260', '322', '461', '284', '271', '224', '553', '463', '544', '394', '224', '481', '332', '159', '605', '440', '203', '269', '500', '404', '268', '313', '262', '438', '77', '196', '509', '321', '466', '274', '133', '225', '332', '254cals', '361', '111,', '106', '276', '253', '15', '279', '273', '509', '428']

 ['1.3', 'trace', '5', '4.4', '10.1', '3.1', '0.9', '4.3', '5.7', '10.1', '0.8', 'trace', '1', '0.7', '2.1', '1.5', '9.1', '7.2', '0.2', '1.6', '3', '2.6', '1.3', '1.1', '0', 'trace', '0.4', '2.2', '2.2', '1.6', '2.2', '7.5', '2.6', '5.1', '4.8', '3.8', '3.6', '3.2', '10.3', '2.4', '0.5', '1.2', '21.7', '3.3', '0.9', '2.6', '0.6', '1.4', '0.8', '8.4', '1.3', '11.4', '1.7', '17.2', '10.2', '2.4', '4.3', '9.2', '3.1', '1.5', '2.6,', '11.4', '1.8', '3.2', '0.9', '4.4', '6.1', '3.2', '1.5', '1.7', '1.5', '0.8', '1.2', '3.5', '1', '10', '1.4', '1', '1.9', '3.8', '2', '3', '0.9', '1.1', '1.2', '1', 'no', '2.3', '0.6', '15.5', '2.4']

 ['29.4', '7.2', '33.1', '55.7', '45.0', '45.3', '5.3', '34.8', '47.8', '44.4', '5.4', '14.3', '8.8', '53.9', '24.2', '19.1', '12.6', '53.8', '10.4', '28.7', '43.0', '12.2', '18.0', '7.7', '5.1', '1.3', '16.9', '11.1', '36.5', '10.8', '11.7', '35.3', '13.1', '61.4', '58.3', '47.2', '34.4', '65.6', '52.1', '13.3', '46.7', '22.4', '21.8', '45.6', '32.9', '30.6', '34.8', '24.0', '39.9', '32.6', '46.1', '31.1', '25.7', '34.1', '38.0', '69.8', '38.7', '9.7', '41.0', '52.0', '16.8', '62.2', '55.6', '8.6', '29.6', '65.6', '48.0', '8.9', '47.1', '17.1', '74.5', '4.6', '12.0', '34.5', '42.4', '63.1', '37.3', '11.5', '21.3', '10.2', '40.2 carbs', '36.5', '7.7', '3.6', '33.3', '41.4', '1.6', '18.6', '40.2', '55.5', '50.6']

 ['12.5', '0.6', '9.6', '7.6', '9.5', '13.5', '3.7', '10.4', '7.8', '5.7', '1.4', '1.5', '6.1', '5.3', '9.9', '2.2', '7.0', '5.7', '1.3', '10.8', '8.6', '5.8', '1.1', '2.1', '0.4', '0.2', '1.7', '6.8', '7.9', '5.9', '6.5', '1.4', '6.6', '7.5', '10.6', '7.4', '10.1', '8.1', '10.2', '9.6', '5.0', '3.1', '3.4', '8.3', '10.0', '16.1', '12.2', '8.5', '9.7', '12.8', '8.0', '2.1', '5.2', '5.9', '2.3', '18.9', '11.5', '4.6', '16.6', '5.4', '1.0', '8.1', '10.3', '3.9', '6.5', '8.9', '6.3', '11.6', '2.0', '7.6', '11.9', '1.6', '6.9', '9.8', '10.1', '5.3', '4', '6.8', '2.3', '2.3', '4.3 fibre', '3.2', '4.6', '4.3', '8.4', '5.3', '0.4', '8.7', '10.8', '13', '6.5 fibre']

 ['0.2', 'trace', '1.8', '0.7', '0.9', '0.2', 'trace salt', '1.6', '0.3', '0.8', 'trace salt', '0.6', 'trace salt', '0.5', '1.2', '0.8', '0.3', 'trace', '0.1', '0.2', '0.1', '1.6', '0.1', '0.9', '0.1', '0.1', '0.4', '0.2', '0.6', '0.1', '0.5', 'trace', '1.2', '1.3', '1', '1.1', '1.6', '1', '1', '0.2', 'trace', '0.5', '0.2', '2.1', '0.1', '0.5', '0.3', '0.7', '0.6', '0.9', '0.2', '0.1', '1.8', '0.6', '1.4', '0.5', '0.2', '0.1', '0.8', '0.8', '0.1', '1.7', '3.3', '2.4', '0.9', '0.3', '2', 'no salt', '1.1', '0.2', '1.7', 'trace', 'trace salt', '2.4', '0.8', '1.3', 'trace', '0.1', '0.9', '0.7', 'trace', '3', '0.1', 'no salt', '1.3', 'trace', '0.2', '0.1', '0.9', '0.4', '1.8']

In [13]:
# Cleaning up nutrition columns df4

# Removing unwanted characters 
df4['Kcal'] = df4['Kcal'].str.replace('cals', '')
df4['Kcal'] = df4['Kcal'].str.replace('kcal', '')
df4['Kcal'] = df4['Kcal'].str.replace(',', '')

df4['SaturatedFat'] = df4['SaturatedFat'].str.replace('no', '0')
df4['SaturatedFat'] = df4['SaturatedFat'].str.replace('trace', '0')
df4['SaturatedFat'] = df4['SaturatedFat'].str.replace(',', '0')

df4['Carbohydrates'] = df4['Carbohydrates'].str.replace(' carbs', '')

df4['Fibre'] = df4['Fibre'].str.replace(' fibre', '0')

df4['Salt'] = df4['Salt'].str.replace(' salt', '')
df4['Salt'] = df4['Salt'].str.replace('trace', '0')
df4['Salt'] = df4['Salt'].str.replace('no', '0')

# Turning data into float
df4['Kcal'] = df4['Kcal'].astype('float64')
df4['SaturatedFat'] = df4['SaturatedFat'].astype('float64')
df4['Carbohydrates'] = df4['Carbohydrates'].astype('float64')
df4['Fibre'] = df4['Fibre'].astype('float64')
df4['Salt'] = df4['Salt'].astype('float64')

print(df4.dtypes)

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein          float64
Carbohydrates    float64
Sugars           float64
Fibre            float64
Salt             float64
Country           object
dtype: object

In [14]:
# Cleaning up nutrition columns df5

print(df5.dtypes, df5.isnull().sum())
df5 = df5.dropna()

# Looking at nutrition columns with data type 'object'

print((df5['Kcal']).tolist(), "\n\n", (df5['Fat']).tolist(), "\n\n", 
      (df5['Carbohydrates']).tolist(),"\n\n", (df5['Salt']).tolist())

Title             object
Ingredients       object
Kcal              object
Fat               object
SaturatedFat     float64
Protein          float64
Carbohydrates     object
Sugars           float64
Fibre            float64
Salt              object
Country           object
dtype: object Title            0
Ingredients      0
Kcal             7
Fat              7
SaturatedFat     7
Protein          7
Carbohydrates    7
Sugars           7
Fibre            7
Salt             7
Country          0
dtype: int64
['230.0', '494.0', '537.0', '465.0', '839.0', '494.0', '401.0', '643.0', '678.0', '573.0', '513.0', '467.0', '798.0', '369.0', '356.0', '574.0', '722.0', '508', '479', '527cals', '242', '491', '531', '421', '404', '574', '501', '722', '586', '533', '459', '397kcal', '808', '276', '767', '444', '739', '796', '350', '416', '213', '360', '441', '580', '406', '648', '511', '628', '354', '507', '394', '488kcal', '801', '406', '713', '224.0', '155.0', '649.0', '663.0', '404.0', '401.0', '231.0', '104.0', '36.0', '247.0', '443.0', '358.0', '358.0', '338.0', '235.0', '448.0', '223.0', '534.0']

 ['7.2', '24.2', '27.1', '18.0', '21.2', '10.7', '21.4', '27.4', '29.5', '19.6', '33.7', '15.5', '40.8', '16.1', '17.0', '15.3', '28.2', '16.9', '28.7', '21.5', '7.0', '21.0', '24.5', '28.7', '14.1', '28.6', '26.6', '43.6', '27.5', '20.7', '28.3', '19.7', '37.2', '9.4', '40.3', '16.1', '58.1', '37', '17.3', '28.8', '5.7', '26.9k', '19.7', '4.3', '15', '24.3', '5.3', '35.7', '13.3', '17.6', '19.4', '21.5', '42.3', '28.4', '27.6', '10.7', '12.4', '30.2', '31.6', '11.4', '22.4', '8.1', '10.2', '1.7', '14.1', '24.3', '15.3', '15.3', '16.2', '7.0', '23.4', '8.1', '28.7']

 ['31.8', '42.5', '54.1', '53.2', '90.3', '52.2', '37.9', '71.9', '49.7', '56.2', '25.8 carbs', '57', '65.3', '41.9', '34.5', '55', '89.7', '28.3', '37.3', '66.2', '13.4', '54.7', '20.8', '26.6', '48.0', '39.5', '32.2', '61.1', '52.1', '17.9', '8.0', '38.7', '75.6', '33.3', '73.7', '41.1', '47.4', '81.8', '17.0', '21.6', '27.1', '18.8', '18.7', '36.7', '48.4', '53.5', '94.5', '47.4', '25.0', '19.6', '37.5', '49.0', '33.4', '18.7', '66.7', '23.4', '0.1', '51.5', '56.9', '48.5', '36.8', '20.0', '2.0', '4.3', '17.3', '19.3', '23.7', '23.7', '44.2', '32.7', '1.0', '31.1', '44.8']

 ['0.7', '1.5', '2.4', '1.9', '3.0', '1.5', '1.2', '1.5', '1.4', '2.1', '1.7', '1.9', '1.0', '1.1', '1.3', '2.8', '1.2', '2.0', '1.4', '1.72', '0.3', '1.8', '1.08', '0.9', '2.0', '1.0', '1.0', '1.1', '0.9', '2.9', '0.6', '2.7', '2.8', '1.3', '2.9', '2.0', '1.3', '0.3', '1.9', '1.4', '0.7', '0.5', '1.8', '1.1', '2', '1.9', '1.9', '1.9', '0.6', '1', '1.7', '1.8', '1.8 salt', '0.5', '1.6', '1', '0.7', '2', '1.3', '2.3', '0.4', '0.6', '0.1', 'trace', '0.8', '0.7', '0.2', '0.2', '0.3', '1.4', '1.6', '0.9', '0.7']

In [15]:
# Cleaning up nutrition columns df5

# Removing unwanted characters 
df5['Kcal'] = df5['Kcal'].str.replace('cals', '')
df5['Kcal'] = df5['Kcal'].str.replace('kcal', '')

df5['Fat'] = df5['Fat'].str.replace('k', '')

df5['Carbohydrates'] = df5['Carbohydrates'].str.replace(' carbs', '')

df5['Salt'] = df5['Salt'].str.replace(' salt', '')
df5['Salt'] = df5['Salt'].str.replace('trace', '0')

# Turning data into float
df5['Kcal'] = df5['Kcal'].astype('float64')
df5['Fat'] = df5['Fat'].astype('float64')
df5['Carbohydrates'] = df5['Carbohydrates'].astype('float64')
df5['Salt'] = df5['Salt'].astype('float64')

print(df5.dtypes)

Title             object
Ingredients       object
Kcal             float64
Fat              float64
SaturatedFat     float64
Protein          float64
Carbohydrates    float64
Sugars           float64
Fibre            float64
Salt             float64
Country           object
dtype: object

In [16]:
# Other operations

In [17]:
# Combine all dataframes into one

frames = [df1, df2, df3, df4, df5]
data = pd.concat(frames, ignore_index=True)
data

# Creating Type column as more appropriate one to mark the cuisine instead of a Country.
# I created that column while scraping before adding vegan recipes.

data['Type'] = 0

# Update Type accordingly for each cuisine
data.loc[data['Country'] == 'India', 'Type'] = 'Indian'
data.loc[data['Country'] == "India", 'Type'] = "Indian"
data.loc[data['Country'] == 'Mexico', 'Type'] = "Mexican"
data.loc[data['Country'] == 'Italy', 'Type'] = "Italian"
data.loc[data['Country'] == 'Spain', 'Type'] = "Spanish"
data.loc[data['Country'] == 'vegan', 'Type'] = 'vegan'

# Drop the Country column
data = data.drop(columns = ['Country'])
data.head()

,Title,Ingredients,Kcal,Fat,SaturatedFat,Protein,Carbohydrates,Sugars,Fibre,Salt,Type
0,Spiced coconut pastries,"1 small cinnamon stick, 4 cardamom pods, 1 bay...",201.0,11.9,5.6,2.0,22.8,6.6,2.4,0.1,Indian
1,Speedy salmon biryani,"300g basmati rice, ½ tbsp vegetable oil, 2 lar...",478.0,10.5,2.7,23.3,70.4,7.9,4.0,0.8,Indian
2,Onion bhajis with yogurt and goat’s cheese dip,"1 tsp cumin seeds, 1 tsp coriander seeds, 1 ts...",112.0,6.2,2.3,5.0,8.0,3.7,2.0,0.5,Indian
3,Falafel curry with spinach,"4 garlic cloves, grated, 4cm piece ginger, gra...",357.0,18.4,2.3,10.7,33.6,10.9,7.1,0.6,Indian
4,Tomato and tamarind fish curry,"2 tsp coriander seeds, 1 tsp cumin seeds, 1 ts...",402.0,16.5,8.3,31.4,29.3,9.6,4.9,1.1,Indian

In [18]:
# The nutritional values seem to be within acceptable range.  
# Note: the quantities are in grams per serving.

data.describe()

,Kcal,Fat,SaturatedFat,Protein,Carbohydrates,Sugars,Fibre,Salt
count,424.000000,424.000000,424.000000,424.000000,424.000000,424.000000,424.000000,424.000000
mean,395.733491,19.259906,6.279009,19.165802,33.067335,8.461557,5.718396,1.087099
std,184.235093,11.196210,5.374558,14.716544,21.942669,6.465446,3.836639,0.927261
min,8.000000,0.100000,0.000000,0.300000,0.100000,0.100000,0.000000,0.000000
25%,253.750000,10.775000,2.300000,7.750000,14.450000,3.700000,2.900000,0.400000
50%,402.500000,17.450000,5.000000,16.350000,31.350000,7.050000,5.200000,0.900000
75%,510.250000,26.825000,8.750000,25.700000,48.925000,11.400000,8.100000,1.600000
max,896.000000,62.000000,33.600000,107.100000,127.400000,39.100000,19.900000,5.600000

In [19]:
# It seems that a number of vegan recipes double as Indian, Italian or other.
#  There are 15 recipes that appear twice.

duplicateRowsDF = data[data.duplicated(['Title'])]
double_titles = duplicateRowsDF.sort_values(by=['Title'])['Title'].tolist()
double_titles

['Black rice paella with artichokes, peppers and spinach',
 'Brazilian black bean soup with raw corn salsa',
 'Cheesy potato frittata with radicchio, salami and olive salad\xa0',
 'Dishoom’s Bhel',
 'Dishoom’s green vada (coriander and mint) chutney',
 'Lighter caponata',
 'Masala cauliflower potatoes',
 'Party pani puri',
 'Pumpkin and coconut pilau',
 'Smoky orange, roasted tomato and olive pappardelle',
 'Super green pasta',
 'Sweet potato and chickpea curry',
 'Tomato and vegetable sauce',
 'Vegan coconut curry',
 'Zuppa di ceci e farro (chickpea and farro soup)']

In [20]:
# A better look into duplicates

data[data['Title'].isin(double_titles)].sort_values(by=['Title'])

,Title,Ingredients,Kcal,Fat,SaturatedFat,Protein,Carbohydrates,Sugars,Fibre,Salt,Type
288,"Black rice paella with artichokes, peppers and...","3 tbsp olive oil, plus a splash, ½ large Spani...",317.0,14.7,2.2,5.8,36.5,5.1,7.9,0.6,vegan
91,"Black rice paella with artichokes, peppers and...","3 tbsp olive oil, plus a splash, ½ large Spani...",317.0,14.7,2.2,5.8,36.5,5.1,7.9,0.6,Spanish
384,Brazilian black bean soup with raw corn salsa,"Sunflower oil for frying, 2 onions, finely cho...",276.0,9.4,1.2,10.3,33.3,10.3,8.4,1.3,Mexican
344,Brazilian black bean soup with raw corn salsa,"Sunflower oil for frying, 2 onions, finely cho...",276.0,9.4,1.2,10.3,33.3,10.3,8.4,1.3,vegan
99,"Cheesy potato frittata with radicchio, salami ...","500g waxy potatoes such as charlotte, cut into...",392.0,24.7,9.9,23.1,17.6,2.6,3.4,1.6,Spanish
255,"Cheesy potato frittata with radicchio, salami ...","500g waxy potatoes such as charlotte, cut into...",392.0,24.7,9.9,23.1,17.6,2.6,3.4,1.6,Italian
16,Dishoom’s Bhel,"½ medium green chilli, chopped, 10g fresh cori...",114.0,3.4,0.4,2.9,16.9,9.6,1.7,0.4,Indian
286,Dishoom’s Bhel,"½ medium green chilli, chopped, 10g fresh cori...",114.0,3.4,0.4,2.9,16.9,9.6,1.7,0.4,vegan
13,Dishoom’s green vada (coriander and mint) chutney,"½ tsp cumin seeds, 20g fresh coriander, 20g f...",8.0,0.2,0.0,0.4,1.3,0.1,0.2,0.1,Indian
285,Dishoom’s green vada (coriander and mint) chutney,"½ tsp cumin seeds, 20g fresh coriander, 20g f...",8.0,0.2,0.0,0.4,1.3,0.1,0.2,0.1,vegan
202,Lighter caponata,"2 aubergines, quartered lengthways, 1 medium r...",248.0,18.6,2.6,3.8,13.1,11.7,6.6,1.2,Italian
292,Lighter caponata,"2 aubergines, quartered lengthways, 1 medium r...",248.0,18.6,2.6,3.8,13.1,11.7,6.6,1.2,vegan
304,Masala cauliflower potatoes,"1 tbsp sunflower oil, 1 tsp black or yellow mu...",252.0,5.6,0.9,12.5,32.9,12.7,10.0,0.1,vegan
33,Masala cauliflower potatoes,"1 tbsp sunflower oil, 1 tsp black or yellow mu...",252.0,5.6,0.9,12.5,32.9,12.7,10.0,0.1,Indian
278,Party pani puri,"400g tin chickpeas, drained and rinsed, 1 larg...",67.0,1.9,0.2,1.5,10.4,4.8,1.3,0.1,vegan
10,Party pani puri,"400g tin chickpeas, drained and rinsed, 1 larg...",67.0,1.9,0.2,1.5,10.4,4.8,1.3,0.1,Indian
9,Pumpkin and coconut pilau,"300g basmati rice, 2 red onions, peeled and cu...",370.0,12.8,7.2,7.2,53.8,10.3,5.7,0.0,Indian
277,Pumpkin and coconut pilau,"300g basmati rice, 2 red onions, peeled and cu...",370.0,12.8,7.2,7.2,53.8,10.3,5.7,0.0,vegan
208,"Smoky orange, roasted tomato and olive pappard...","8 ripe tomatoes, roughly chopped, 1 orange, cu...",529.0,21.2,3.2,14.9,65.6,10.7,8.1,1.0,Italian
297,"Smoky orange, roasted tomato and olive pappard...","8 ripe tomatoes, roughly chopped, 1 orange, cu...",529.0,21.2,3.2,14.9,65.6,10.7,8.1,1.0,vegan
325,Super green pasta,"500g penne pasta, 200g pot of houmous, 1 avoca...",500.0,18.0,4.4,15.0,65.6,3.2,8.9,0.3,vegan
242,Super green pasta,"500g penne pasta, 200g pot of houmous, 1 avoca...",500.0,18.0,4.4,15.0,65.6,3.2,8.9,0.3,Italian
59,Sweet potato and chickpea curry,"1 tbsp light olive oil, 1 large red onion, fin...",509.0,23.4,15.5,12.7,55.5,18.2,13.0,0.4,Indian
349,Sweet potato and chickpea curry,"1 tbsp light olive oil, 1 large red onion, fin...",509.0,23.4,15.5,12.7,55.5,18.2,13.0,0.4,vegan
184,Tomato and vegetable sauce,"4 tbsp extra-virgin olive oil, ½ onion, finely...",113.0,7.8,1.1,1.9,7.7,6.9,2.1,0.9,Italian
283,Tomato and vegetable sauce,"4 tbsp extra-virgin olive oil, ½ onion, finely...",113.0,7.8,1.1,1.9,7.7,6.9,2.1,0.9,vegan
276,Vegan coconut curry,"2 tbsp light olive oil or coconut oil, 2 x 280...",386.0,24.3,9.1,25.3,12.6,5.6,7.0,0.3,vegan
6,Vegan coconut curry,"2 tbsp light olive oil or coconut oil, 2 x 280...",386.0,24.3,9.1,25.3,12.6,5.6,7.0,0.3,Indian
316,Zuppa di ceci e farro (chickpea and farro soup),"800g dried chickpeas, 2-3 fresh sage sprigs , ...",394.0,15.9,4.3,18.3,38.7,2.8,11.5,0.2,vegan
231,Zuppa di ceci e farro (chickpea and farro soup),"800g dried chickpeas, 2-3 fresh sage sprigs , ...",394.0,15.9,4.3,18.3,38.7,2.8,11.5,0.2,Italian

In [21]:
# Counting the recipes in each Type of cuisine.

data.groupby('Type')['Title'].count()

Type
Indian     88
Italian    88
Mexican    73
Spanish    84
vegan      91
Name: Title, dtype: int64

In [22]:
# Keeping the last duplicate whcn dropping saves all Mexican recipes (they are 
# fewer than the other Types).

data = data.drop_duplicates(subset='Title', keep="last")
data.groupby('Type')['Title'].count()

Type
Indian     81
Italian    83
Mexican    73
Spanish    82
vegan      90
Name: Title, dtype: int64

In [23]:
# Doublecheck the data

data.describe()

,Kcal,Fat,SaturatedFat,Protein,Carbohydrates,Sugars,Fibre,Salt
count,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000,409.000000
mean,399.305623,19.472616,6.357213,19.488264,33.151711,8.491687,5.693888,1.106186
std,184.108336,11.237592,5.393733,14.813407,21.978450,6.520362,3.836964,0.933940
min,8.000000,0.100000,0.000000,0.300000,0.100000,0.100000,0.000000,0.000000
25%,260.000000,11.000000,2.300000,8.100000,14.500000,3.700000,2.900000,0.400000
50%,406.000000,17.600000,5.100000,16.900000,31.100000,7.100000,5.100000,0.900000
75%,513.000000,27.100000,8.900000,26.000000,48.900000,11.400000,8.000000,1.600000
max,896.000000,62.000000,33.600000,107.100000,127.400000,39.100000,19.900000,5.600000

In [24]:
# Save dataframe to csv file

data.to_csv("../data/recipes_clean.csv")